FaithLife-Community/OuDedetai

.github/workflows/autobuilds.yaml, .gitignore
- Remove user-built `dist/LogosLinuxInstaller` from
- Add GitHub Action to build on demand.
=> add GH autobuild action

LogosLinuxInstaller.py, config.py, gui.py, gui_app.py, utils.py
=> Add `-K|--skip-dependencies`. Fix #49.

config.py, msg.py
Fixes #66 
- Use `pathlib.Path` to make sure `~/.local/state/Logos_on_Linux` folder exists when logfile is created.
- I also snuck in some pep8 linting cleanup in `msg.py` and `config.py`.
=> Ensure log file's parent folders exist.

gui_app.py
Fixes #72 
Worked correctly when tested with no config file and no existing install.
=> Properly update app button in GUI after install is complete

gui.py, gui_app.py, installer.py, utils.py
Fixes #58 
- Run wine exe check in thread
- Add default text to drop-down menus (sufficient in lieu of changing background color?)
- Auto-populate release list and exe list once product and version are set
=> GUI Enhancements

gui_app.py, tui.py, tui_app.py, utils.py
- Fix problem where TUI wasn't returning user's choice.
- Prevent self-update from running when in "script" mode.
=> Alpha.4.1 hotfix

utils.py
Fixes #110 
Had to change how releases_xml gets handled, as well as json_data from GitHub, but testing with a clean install was successful.
=> Handle Logos releases XML with BOM

wine.py
Now the installation works for me on Ubuntu 24.04
=> Fix import typo and missing directory

config.py, installer.py, main.py, msg.py, tui_app.py, tui_curses.py, tui_dialog.py, tui_screen.py
Fix #124
- Update tui_screen print strings
- Fix divide by 0 issue
- Switch to use of queues for choice processing
- Switch to use of queues for screen stacking/switching
- Disable curses try/except errors for fuller debugging
- Switch to which_dialog_options
- Fix display issues and menu switching
=> Fix TUI Issues

gui_app.py
Fixes GUI not correctly falling back to recommended appimage file in alpha.13 release.
=> correctly default to recommended binary

config.py, gui.py, gui_app.py, installer.py, main.py, msg.py, network.py, system.py, tui_app.py, tui_curses.py, tui_screen.py, utils.py, wine.py
This PR will aim to resolve #123 and #138.
I also did a lot of code clean up.
=> Config File Issues

README.md
Corrects spelling in "scrips" -> "scripts" and a few grammatical mistakes.
Yours in Christ,
James
=> Correct ensure-venv command

installer.py
I don't know of any code paths to trigger this error, however app may be uninitiated at this point
=> fix: ensure app is set before attempting to operate on it

system.py
=> Add OpenSUSE Support

ou_dedetai/tui_app.py
Looks like some renames didn't get picked up in the first wave
=> fix: complete wine refactor

ou_dedetai/cli.py, ou_dedetai/gui_app.py, ou_dedetai/installer.py, ou_dedetai/tui_app.py, ou_dedetai/wine.py
This is the last part needed to fix https://github.com/FaithLife-Community/LogosLinuxInstaller/issues/191
Utilities -> Install ICU files
Use flag `--install-icu`
- App actions -> Install/update ICU files
- Run Action
=> fix: update out of date icu files

Dockerfile
slightly more cli friendly
also combine the two apt-gets (slightly smaller image size on disk)
=> refactor: use apt-get in dockerfile

ou_dedetai/config.py, ou_dedetai/main.py
=> fix: migrate config from old location to new

ou_dedetai/cli.py, ou_dedetai/config.py, ou_dedetai/control.py, ou_dedetai/gui_app.py, ou_dedetai/installer.py, ou_dedetai/system.py, ou_dedetai/tui_app.py, ou_dedetai/utils.py
Resolving some of the comments from here https://github.com/FaithLife-Community/LogosLinuxInstaller/pull/205
=> refactor: handfull of fixmes resolved trivally

ou_dedetai/logos.py, ou_dedetai/system.py, ou_dedetai/wine.py
=> Fix #17. Add Alpine Support

CHANGELOG.md, ou_dedetai/system.py
=> fix: remove pacman --overwrite flag

ou_dedetai/logos.py
When deleting the application update, there are entries added to the UpdateUrls table which should be cleared to prevent bloat, however when normal resources are downloaded the UpdateUrls table is also updated.
I failed to test downloading new resources with the original code.
Tested:
- v38.1 installation hitting the download updates banner. Downloads the book updates, but not the application update
- v38.1 install downloading new books from the library pane
- clean v39.1 install downloading resources. Both initially and additional in the library tab after download
and also fixed a bug where if the process kill for logos stop fails, it wouldn't set logos state properly
Fixes: #275 #262
=> fix: only remove unused updateURLs

ou_dedetai/wine.py
We have been relying on a combination of `wine64 --version` and finding a string like `wine-devel` in `lib64/wine/x86_64-windows/mscoree.dll` to determine the full wine release. However, the string in `mscoree.dll` is actually dependent on the build directory name when wine is built. This results in the branch name in a custom build's `mscoree.dll` not being recognized, or being wrongly determined (e.g. in https://github.com/sil-car/wine-builds/releases/tag/wine_10.0 the branch was evaluating to "builds" b/c the build directory is called `wine-builds` instead of `wine-devel` or `wine-stable`).
WineHQ [version naming convention](https://gitlab.winehq.org/wine/wine/-/wikis/Wine-User's-Guide#wine-from-winehq) says that there are 3 possible branch names: `stable`, `devel`, and `staging`. The …
=> fix: unrecognized branch with custom-built wine

ou_dedetai/tui_app.py
Tested:
- Resized using method that didn't work using main branch, after ~1s it resizes
- Resized using method that did work on main branch, it resizes imminently
=> fix: handle resize when terminal doesn't send SIGWINCH

CHANGELOG.md, ou_dedetai/constants.py
Tested:
- clean install and run up to login page
=> chore: release 4.0.0-beta.8

ou_dedetai/tui_app.py, ou_dedetai/tui_curses.py, ou_dedetai/utils.py
=> fix: disappearing TUI lines

ou_dedetai/config.py
Creates a portable config under the install_dir, positioned at top for ease of finding.
Refactors the write_config function by adding a write_json_file function.
=> refactor: create portable config

ou_dedetai/gui.py
Fixes: #312
Needs testing, code written on phone
=> Fix: wrap progress bar messages

ou_dedetai/config.py, ou_dedetai/network.py
Fixes: #333
Tested:
- removed config and network cache
- launched GUI
- observed Install buttons start off disabled, then enable themselves
=> fix: also call config update hook when network cache gets populated

CHANGELOG.md, ou_dedetai/constants.py
Put most important changes on top in bold that user may care about
Tested:
- clean install from source code all the way to opening "copy bible verses" on debian 12
=> chore: update to 4.0.0-beta.9

ou_dedetai/config.py, ou_dedetai/installer.py, ou_dedetai/tui_app.py
Accidentally forced a bad push to #324. Restoring it here.
=> refactor: Add TUI default and advanced install options

ou_dedetai/app.py, ou_dedetai/cli.py, ou_dedetai/config.py, ou_dedetai/constants.py, ou_dedetai/control.py, ou_dedetai/gui.py, ou_dedetai/gui_app.py, ou_dedetai/main.py, ou_dedetai/network.py, ou_dedetai/tui_app.py, ou_dedetai/tui_curses.py
Fixes: #274, #103
Still need to test one last time with all 6 combinations (GUI, TUI, CLI), (default and customer dirs), as well as all 3 buttons
=> feat: generate support bundle

ou_dedetai/app.py, ou_dedetai/cli.py, ou_dedetai/control.py, ou_dedetai/gui.py, ou_dedetai/gui_app.py, ou_dedetai/tui_app.py
Implement `App._info`  method for displaying info to user that doesn't require follow-up action.
Tested:
- GUI: Get Support > accept default > Show links
- GUI: Advanced Install
- TUI: Get Support > accept default > Show links
=> feat: generic info message

ou_dedetai/constants.py
Write code on phone, still needs testing
=> fix: ensure FL-Community is in path when no XDG_DATA_DIR is set

ou_dedetai/network.py
Display to the user how long they have left until the rate limit expires
Tested:
- Hit github api repeatedly using `curl -v https://api.github.com/repos/FaithLife-Community/wine-appimages/releases/latest`
- Cleared network cache
- Used OD to install
- Observed user friendly `2025-03-06 22:50:11 ERROR: GitHub API rate limit exceeded. Please wait 54 minutes before trying again.` in the log, despite traceback not showing this helpful message (that will have to wait on https://github.com/FaithLife-Community/OuDedetai/issues/300)
=> fix: github rate limit timer

.github/workflows/build-snap.yml, snap/snapcraft.yaml
successful run here: https://github.com/ctrlaltf24/OuDedetai/actions/runs/13528272169
=> ci: add job to build snap

ou_dedetai/app.py, ou_dedetai/backup.py, ou_dedetai/config.py, ou_dedetai/constants.py, ou_dedetai/database.py, ou_dedetai/gui.py, ou_dedetai/gui_app.py, ou_dedetai/installer.py, ou_dedetai/logos.py, ou_dedetai/main.py, ou_dedetai/network.py, ou_dedetai/repair.py, ou_dedetai/system.py, ou_dedetai/tui_app.py, ou_dedetai/tui_curses.py, ou_dedetai/tui_dialog.py, ou_dedetai/tui_screen.py, ou_dedetai/utils.py, ou_dedetai/wine.py, pyproject.toml, tests/test_utils.py
Did not make functional changes.
It's possible there is a typo somewhere
Tested:
- clean install
- run app
=> style: increases allowed line length to 120

ou_dedetai/gui_app.py
The TUI already has this behavior
Tested (40.2 clean install pre-login):
- Started OD with app installed, but not running -> Run Logos shown
- When "Run Logos" is hit, button switches to "Stop Logos"
- When Logos was launched using OD, but is closed independently of OD, button switches to "Run Logos" after the app closes
- "Run App" -> Switches to "Stop App", when "Stop App" is clicked, it stops Logos and switches to "Run Logos", when "Run Logos" is hit again, it launches
- GUI when Logos isn't installed no errors seen on console
- When Logos is installed via the GUI, button switches from "Install" to "Run Logos". Hitting that switches to "Stop Logos", hitting that switches to "Run Logos" which launches Logos
=> feat: support Stop app operation on GUI

ou_dedetai/system.py
I only fixed the Arch side of things as I don't have a way to test SteamOS, however, I would assume that it needs changed as well. This fixes issue #398, which I filed just before fixing it when I was unsure on whether or not I could get a dev environment set up.
=> Replace p7zip with 7zip on Arch (Fixes #398)

ou_dedetai/network.py
Observed by some users on protonvpn specifically that for some reason the .msi installer only downloads partially. Try again until download completes
Tested:
- Used VPN where this occurred and went through install process
- the curl equivalent of this patch: `while ! curl -C - -S -v -o out https://downloads.logoscdn.com/LBS10/Installer/44.1.0.0002/Logos-x64.msi; do sleep 0; done`
Fixes: #415
=> fix: retry download if partial

ou_dedetai/control.py
slightly helpful when debugging, we'll still need more information than this to properly debug, but it's a start
We can wait for more info or merge multiple PRs, I'm fine either way
=> feat: include mime queries in support package
