FaithLife-Community/OuDedetai

utils.py
This has been confirmed fixed by @savionlee in the [Issue tracker](https://github.com/FaithLife-Community/LogosLinuxInstaller/issues/9#issuecomment-1872567329)
=> fix #9: gzip server reply gives compressed file size instead of disk size

utils.py
A user has [confirmed](https://github.com/FaithLife-Community/LogosLinuxInstaller/issues/10#issuecomment-1872573869) that this fix works.
=> Fix #10: sharedlibs verification via ldconfig requiring sudo for some systems

LogosLinuxInstaller.py, config.py, installer.py, msg.py, utils.py
Rather than log an error and exit if the config file can't be decoded as JSON, assume that it is a plaintext legacy config file. Read it line-by-line, assuming the key/value separator is '='.
I added an if statement (L112-L114) to remove any comments found *after* the `key=value` text, like `key=value # comment`, but maybe that's an unlikely (or even impossible) scenario?
This doesn't fully close #6, since there is a bigger discussion going on there, but it would at least remove the roadblock to proper script execution.
=> config fixes: import legacy, save as JSON

LogosLinuxInstaller.py, app.py, control.py, gui.py, installer.py
This commit fixes #4.
It also places the TUI app in a while loop and moves the quick launch code behind an `if GUI` check.
Depends on #29.
=> Add an Option to Redownload Winetricks

utils.py, wine.py
For system (non-AppImage) wine, `mscoree.dll` is assumed to be relative to the wine binary:
```
wine64/../../lib64/wine/x86_64-windows/mscoree.dll
```
For AppImage wine, it's found by mounting the AppImage, then glob searching for `**/lib64/**/mscoree.dll`.
The AppImage must be Type 2 (see [AppImage spec](https://docs.appimage.org/reference/specification.html#development) and [draft.md](https://github.com/AppImage/AppImageSpec/blob/master/draft.md))
This has been tested with winehq-stable branch and with the current preferred AppImage found at https://github.com/FaithLife-Community/LogosLinuxInstaller/releases/download/wine-devel-8.19/wine-devel_8.19-x86_64.AppImage
However, I don't think the AppImage's branch is ever actually checked in the script at this point. I'll leave that check for …
=> Get wine branch using mscoree.dll - Fixes #32

CHANGELOG.md, LogosLinuxInstaller.py, app.py, config.py, installer.py, utils.py
Fixes #3.
The install routine for dependencies was broken. I had to test this heavily on my pacman machine but I got it working.
This PR thus fixes the install dependencies routine and adds an optarg, a TUI, and a GUI to run the check_dependencies() function.
Depends on #31.
=> Add an Option to Reinstall Dependencies

gui_app.py
Installer fails to run in GUI mode because `self.sys_winetricks` is incorrect variable name.
Fixed to `self.gui.sys_winetricks`.
=> fix bad variable definition

config.py, installer.py, utils.py
Partial fix for #5. This adds the ability to remove AppImage Launcher.
Add `config.PMC_REMOVE`; remove yum
Add `config.BADPACKAGES`
Add `query_package()` "mode" var, add `remove_packages()`, add `check_bad_packages()`
I've also made sure to add a major warning label to this remove command to its destructive capability.
One thing we may need to add is an exit function to the AppImageLauncher detection. If it is found, Logos won't be able to launch, and the install should fail at that point, otherwise we will wind up having support requests.
If the user removes it, the install should exit and instruct the user to reboot, or offer to reboot the system for the user but with warning.
=> Add ability to detect and remove AppImageLauncher

.gitignore, LogosLinuxInstaller.py, gui.py, gui_app.py, installer.py, msg.py, tui.py, tui_app.py, utils.py
This is a partial fix for #5. It adds conditional logic to the CLI, TUI, and GUI that either removes or disables a function if the config file states that the Logos install was created with something other than an AppImage.
It also creates a new GUI tooltip function. This is applied to the set appimage button, so that when the user hovers over it with his mouse, it will tell him why the button is disabled.
=> Disable setappimage if winebincode != AppImage

installer.py, utils.py
Fixes #61 
I tested these cases while tethered to my phone: "no connection" meant I had turned off the USB connection, "timeout" was simulated by keeping the USB connection active but turning off my phone's data connection. I think this is realistic enough testing for the time being.
=> Gracefully handle bad internet connection

LogosLinuxInstaller.py, utils.py
This subcommand wasn't working correctly, and it required that `TARGETVERSION` be set. These changes allow any user or potential user to simply run `LogosLinuxInstaller --install-dependencies [-D]` and report back any errors, without having to try to install Logos or Wine.
- fix typo in `LogosLinuxInstaller.py`
- default to `TARGETVERSION = 10` if not set by user
=> Allow `--install-dependencies` to run on a clean install

scripts/ensure-python.sh
The script aborted since 'read -pr "str" ans' is not valid syntax.
=> ensure-python.sh: correct shell script

gui_app.py, installer.py, tui_app.py, utils.py
If an Ubuntu user is running the GUI and needs dependencies installed, the installer will hang because it's waiting fruitlessly for a `sudo` password. The user would only maybe notice this if they start the installer from the terminal, which not a typical use-case for the GUI. Otherwise the prompt is unreachable. This change prioritizes `pkexec` over `sudo`, because `pkexec` will pop up a graphical password prompt. I think this will also give a graphical prompt for a user running the TUI, if there's an available display, otherwise it will fallback to a terminal prompt.
The 2nd change is making sure the TUI checks for "Install dependencies" before checking for a choice that starts with "Install". The original order meant that if the user selected "Install dependencies" from the menu, it …
=> Fix Install Issues

utils.py
This continues work on #1. This update seeks to fix Manjaro deps by removing deps from the original Bash source.
- bc, libxml2 are no longer needed due to Python
- cabextract is for Logos 9
- patch I believe was also Logos 9, but I don't know what for
This needs verification but we should be able to remove sed and grep unless winetricks needs them, per #90.
We may also need to add `patch` to Logos 9 requirements, but I don't think so?
Perhaps curl can be removed? Perhaps also wget?
=> Update Manjaro Deps

README.md, utils.py
This fixes two minor issues I found while trying to install on Ubuntu 22.04. Note that `ensure-python.sh` doesn't work on Ubuntu 22.04 yet, since winehq-staging is not found in the repo added to apt. But I think these two bugfixes are still worth merging.
=> Update Debian and Ubuntu Deps

CHANGELOG.md, config.py, gui.py, gui_app.py, installer.py, main.py, tui_app.py, tui_curses.py, tui_screen.py, utils.py, wine.py
Should fix #121.
Also implements a check for the currently installed Logos version and sets the Logos 10 minimum Wine version appropriately.
We can then use this function in future code to add an update Logos routine for #116 or to display the current version in the TUI/GUI, etc.
It also fixes an issue with tui_dialog.tasklist and makes the TUI app display the currently installed Logos version.
=> Fix #121, #124. Prep for #118.

msg.py, network.py
Fixes #132 with gzipped rotation for logs of 10MB in size.
=> Add log rotation. Fix #132.

Dockerfile, README.md
Instead of setting up Python 3.12 on the machine itself, this allows users to use Docker to generate the relevant Linux binaries.
Example output:
```
$ sudo docker run --rm -v $(pwd):/usr/src/app logosinstaller
Collecting pyinstaller
Downloading pyinstaller-6.10.0-py3-none-manylinux2014_x86_64.whl.metadata (8.3 kB)
Collecting altgraph==0.17.4 (from -r requirements.txt (line 1))
Downloading altgraph-0.17.4-py2.py3-none-any.whl.metadata (7.3 kB)
Collecting certifi==2023.11.17 (from -r requirements.txt (line 2))
Downloading certifi-2023.11.17-py3-none-any.whl.metadata (2.2 kB)
Collecting charset-normalizer==3.3.2 (from -r requirements.txt (line 3))
Downloading charset_normalizer-3.3.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (33 kB)
Collecting distro==1.9.0 (from …
```
=> Add Dockerfile for building with Python 3.12

config.py, gui.py, gui_app.py, installer.py, msg.py, network.py, system.py, tui_app.py, tui_curses.py, tui_screen.py, utils.py, wine.py
This PR helps to fix at least one of the issues in #143.
I've also swapped the choice processor to using a dict to make it easier to understand or even reuse code, as per #146.
I've also added in the ability to switch the TUI's color scheme. See bottom of main menu for button.
I've also fixed its vertical and horizontal resizing and made it so the console log grows in size, too.
This PR also adds in submenus to the TUI to reduce the number of options in any single menu.
Implements a config and a TUI solution to fix #84 and #157.
This PR resolves #106 for the TUI.
This PR also adds in logging deduplication, to avoid unnecessary additional logs.
=> Partial fix for #143; TUI Improvements; Resolve #84; #106; #157

cli.py, control.py, gui_app.py, installer.py, main.py, msg.py, network.py, system.py, tui_app.py, utils.py, wine.py
Fixes #128. Requires #158.
I should clarify my aim is to get it working and to make it pretty later (cf. #172).
Part of my goal in this PR is to make #147 potentially easier. The CLI is intentionally aiming to be a highly simplified event/queue manager, thus I aim to clear the event's status frequently in order to reuse it later. The TUI is, to my knowledge, never waiting on more than one event at a time. Therefore we have not need to have multiple events. If we do have some place where we are waiting on multiple, then we can have two different ones at that time. This would make the code much simpler, leaner, and easier to reuse.
What I imagine therefore, from this PR, is extracting all the event/queue code from the TUI, the CLI, and the GUI, into its own class module.
=> Campaign to Save the CLI

README.md
There is no ./main.py anymore. Perhaps we should re-word this documentation to use the pypi package instead
=> docs: update README with new invocation

ou_dedetai/network.py, ou_dedetai/wine.py
In some cases the first release may be a pre-release or otherwise may not be the latest.
Use the /latest url to get the "latest" according to github
Needed to pull 72.1-custom from https://github.com/FaithLife-Community/icu/releases
=> fix: pull latest github release

ou_dedetai/cli.py, ou_dedetai/config.py, ou_dedetai/control.py, ou_dedetai/installer.py, ou_dedetai/network.py, ou_dedetai/system.py, ou_dedetai/utils.py, ou_dedetai/wine.py
Small handful of comments on things I noticed while reading
No functional changes
=> refactor: add type hints and comments

CONTRIBUTING.md, README.md
As a user I didn't realize there was a simple way without git cloning when I first saw the project
Make the easy way easier to find.
The first commit has no edits, just a move, the second commit has the edit
=> docs: move complex install instructions out of README

ou_dedetai/network.py, ou_dedetai/wine.py
This renames the installed icu tarball to include the version
Pros:
- removes need for state file
- doesn't rely on the name of the released icu tarball
- similar handling to how we download the Logos msi installer today
Cons:
- can't think of any
Fixes: #220
cc: @n8marti and @thw26
=> feat: use ICU tarball name as version

ou_dedetai/installer.py
Workaround:
```
mkdir -p ~/.local/share/applications
```
Fixes: #230
=> fix: ensure local desktop file directory exists

ou_dedetai/system.py, ou_dedetai/utils.py, scripts/distro-info.sh
- fix #229
- update dependency package names for newer debian-based distros
- remove `cabextract` and `sed` dependencies b/c they're included in the wine appimage
I will test this in debian/ubuntu/fedora VMs before removing "draft" status. I trust others will test other distros as needed :wink:.
EDIT: Explicit requirements seem to be:
- `fusermount` command
- *some* kind of `libfuse*.so`, but must be compatible with the `fusermount` binary
This is complicated because Ubuntu symlinks `/bin/fusermount` to `/bin/fusermount3`, so it only needs the `fuse3` package, which provides both `fusermount` and brings in `libfuse3-3` as its own dependency, which is the library compatible with that `fusermount` (which is really`fusermount3`). But then other distros (e.g. fedora) keep fuse 2 and 3 …
=> make dependencies lists more precise

ou_dedetai/config.py, ou_dedetai/main.py, ou_dedetai/system.py
This PR is a WIP draft working to implement ELF interpreter support from [box64](https://github.com/ptitSeb/box64) and/or [FEX-EMU](https://github.com/FEX-Emu/FEX) and/or [Wine Hangover](https://github.com/AndreRH/hangover) in order to be able to install current Logos 64bit versions on Linux 32 bit, ARM 32 bit, ARM 64 bit, RISC-V 32 bit and RISC-V 64-bit.
The current code errors during install and exits the program if the architecture is not x86_64.
Technically the ELF interpreters could let us install modern Logos 10 on x86 machines (not x86_64).
cf. #24 
The initial PR is to get the basics in place for us to play with.
---
UPDATE: 20241126
As of the most recent commits to box64 (~9/20), ou dedetai built with pyinstaller now loads.
A test of Wine Hangover 9.20 suggests that it is in fact …
=> Add Architecture Detection

ou_dedetai/network.py
An update to logos 39 breaks the install, as well as a fresh install fails
=> fix: disable updates to logos 39, currently broken

scripts/quick-install.sh, scripts/quick-run.sh, scripts/sample-config.json
The purpose of these two scripts is to facilitate easy testing of the wine setup.
- `scripts/quick-install.sh` installs and configures the wine system
- `scripts/quick-run.sh` launches the installed Logos app
There is currently very little data validation, and the user is responsible for setting up the host system and downloading all necessary files to `~/Downloads` beforehand. The scripts rely on 3 environment variables, which are requested interactively if not already set:
- `LOGOS_RELEASE_VERSION`: e.g. 38.1.0.0002
- `LOGOS_WINEPREFIX`: e.g. `~/LogosBible10`
- `LOGOS_WINE`: e.g. `/opt/wine-devel/bin/wine64`
=> add quick-install|run scripts for easier testing

CHANGELOG.md, ou_dedetai/installer.py, ou_dedetai/utils.py
Fixes issue where new appimage would be downloaded with the wrong name and moves the recommended appimage to the top of the list
Reproduction:
- install when there is an older recommended appimage
- delete LogosBible10 folder
- attempt install again
Expected behavior: new appimage downloads with correct name
Actual behavior: appimage downloads with the old name
=> fix: appimage download issues

ou_dedetai/gui_app.py, ou_dedetai/network.py, ou_dedetai/utils.py
Fix #273
Use `packaging.version.Version` to compare version numbers, which allows for `major.minor.hotfix` format, as well as `major.minor` format, and is in other ways more flexible than integer or float comparisons.
=> Fix AppImage update procedure in GUI

ou_dedetai/installer.py, ou_dedetai/wine.py
This fixes #286. It seems the appimage would work fine with the hard-coded windows path `C:\LogosStubFailOK.mst`, but this was failing when using system wine. But using `winepath -w` to convert the original MST file path to a winepath, and ensuring that the path is not quoted, succeeds. In fact, it's probably the lack of quotes that solves the problem, but this also adds a simplification in not needing to copy the MST file into the WINEPREFIX before using it.
=> fix: convert MST file to windows path before use (#286)

ou_dedetai/config.py, ou_dedetai/control.py, ou_dedetai/logos.py, ou_dedetai/system.py, ou_dedetai/wine.py
Fixes: #292 #143 #236
Didn't test:
- alpine
Tested:
- user that was able to reproduce #292 tested and it works for them
- running integration.run_cmd(["env") from a pyinstaller binary (with and with LD_LIBRARY_PATH set), observed LD_LIBRARY_PATH did not include tmpdir
- running system.run_command(["env") from a pyinstaller binary (with and with LD_LIBRARY_PATH set), observed LD_LIBRARY_PATH did not include tmpdir
- running system.run_command(["env") from a pyinstaller binary (without LD_LIBRARY_PATH set), observed LD_LIBRARY_PATH was not set
- clean install & run - login page showed successfully (install procedure calls popen_command, and run_command)
- built pyinstaller binary and ran on fedora 40 doing a clean install via TUI. login screen shown!
- built pyinstaller binary and ran on …
=> fix: remove pyinstaller from LD_LIBRARY_PATH when shelling out

ou_dedetai/config.py, ou_dedetai/tui_app.py
Fixes #259.
There were two issues:
- the legacy config value was wiping out the new config value
- the config's init function, in the call to the legacy config, was setting a default value, thus overriding reading the config
To fix these:
- I changed the tui color scheme variable name to differentiate it
- I removed the setting of the default value
- I checked for a None value, which is coming from the legacy config
---
To remove the None check, a default value needs to be established, but setting the default value in the legacy config is causing an existing config's set color scheme to be ignored in favor of the default.
---
This PR also fixes the Logos color scheme: its value was improperly set.
This PR also adds the System color scheme.
---
This needs further work though as sometimes …
=> fix: fix setting tui color scheme

ou_dedetai/config.py, shell.nix
This python package list should not be considered up-to-date, see pyproject.toml for the latest.
Sets all envs needed for running on NixOS
Also fixed bug where WINE_EXE wasn't respected
on nix simply run `nix-shell` and it will download the python dependencies as well as wine needed for Logos on NixOS
Tested:
- Install on NixOS (TUI)
- Noticed that the TUI "Run Logos" button didn't work the first time, had to re-launch OD
- Noticed after logging in, when hitting "Continue" after selecting Download All Resources, Logos crashed, but recovered after launching again
Didn't see any indication the above bugs were NixOS specific and they were easily recoverable.
=> feat: add nix-shell

ou_dedetai/logos.py, ou_dedetai/tui_app.py
Fix: #278
remove unneeded TUI queues
also removed a clear/refresh in update_main_window_contents that may been the race condition we were looking for. This is done in draw. It renders correctly
Tested:
- Clean install of Logos and run
- changing color scheme over and over again
- navigating into utilities menu and back again
- resizing screen super small (both horizontal and vertical), screen to small was shown
=> fix: TUI color scheme cycle hang

snap/bin/run.sh
The path used to search for the installed app was incorrect, which triggered installation on every run. Thankfully our installer verifies each step along the way, so nothing actually gets installed again. But this short-circuits running unnecessary code.
=> fix: bad path leading to oudedetai running installer every time

ou_dedetai/config.py, ou_dedetai/constants.py, ou_dedetai/gui.py, ou_dedetai/installer.py, ou_dedetai/system.py, ou_dedetai/utils.py
Fixes #53.
Removes Logos 9 support. Since the FLPRODUCT version in @ctrlaltf24's abstract class refactor is now acquired through the config, all we need to do is have it return 10 no matter what.
I've left the question in code in order to maintain should we need it in the future. I don't think we will since Logos has moved towards a semi-SaaS model.
=> chore: remove Logos 9 support

ou_dedetai/config.py
The recent removal of Logos 9 support led to a change where the installer fails to fall back to the correct default Faithlife product version. There is a conditional check for a value that doesn't exist. This change makes the fallback explicit, without the conditional check.
=> fix: return current version "10" if not overridden

ou_dedetai/config.py
Only return 10 if the user hasn't selected something else
Tested:
- set faithlife_product_version to 9 in config
- ran installer
- observed asking for logos 9 target versions
- observed "Logos 9 is not supported" then exit
Also tested:
- removed faithlife_product_version from config
- export TARGETVERSION=9
- ran installer
- observed asking for logos 9 target versions
- observed "Logos 9 is not supported" then exit
=> fix: don't clobber user's faithlife_product_version

ou_dedetai/app.py, ou_dedetai/config.py, ou_dedetai/gui_app.py, ou_dedetai/main.py, ou_dedetai/tui_app.py, ou_dedetai/wine.py
Another route we could go is always doing a passive install, as now we have the proper EULA checks
Fixes: #241
Tested:
Scenario CLI passive:
- passed args --install-app --passive
- Asked on CLI to agree to the EULA
- install MSI success
Scenario CLI assume yes:
- passed args --install-app -y
- Installer exits requiring the --i-agree-to-faithlife-terms flag
Scenario CLI assume yes agreed to terms:
- passed args --install-app -y --i-agree-to-faithlife-terms
- Install MSI success
Scenario GUI passive:
- passed env DIALOG=tk and args --passive
- Asked on the GUI to agree to the EULA
- accepted
- install MSI success
Scenario GUI passive decline:
- passed env DIALOG=tk and args --passive
- Asked on the GUI to agree to the EULA
- declined
- Error dialog, then exit
Scenario TUI passive:
- passed …
=> fix: ensure user agrees to the EULA even in non-interactive settings

ou_dedetai/config.py, ou_dedetai/constants.py, ou_dedetai/gui.py, ou_dedetai/gui_app.py, ou_dedetai/main.py, ou_dedetai/repair.py, snap/bin/run.sh
Leverages the generic nature of App to create a dialog that just does the installation
Useful in flatpak/snap if we want to start the install process and show the user feedback in a GUI fashion
Tested:
- setting DIALOG=tk
- passing arg --install-app
- observed install window opened, and install success
Also tested:
- setting DIALOG=tk
- passing neither -C or --install-app
- observed control panel opened
=> feat: add install GUI

ou_dedetai/main.py
Add WINEDEBUG flags when the --debug cli argument is passed. None of these are excessively verbose
=> feat: add winedebug flags

ou_dedetai/cli.py, ou_dedetai/config.py, ou_dedetai/constants.py, ou_dedetai/gui_app.py, ou_dedetai/installer.py, ou_dedetai/main.py, ou_dedetai/system.py, ou_dedetai/wine.py
Needed to restore winetricks, however kept as much of non-winetricks as already existed in the code.
Fixes: #335
Removed support for winetricks from the system - no need, the bash script is small
Also checked winetricks exit code (we didn't do this before), to detect when winetricks fails
Restored winetricks binary download, this time using the appimage if found, if not download. Also changed the winetricks version to roughly match appimage for consistency
It should be noted I added cabextract package as a dependency to most OS' that was not there before - unsure how it worked before this.
- ~~[ ] appimage (unsupported)~~ (There is no user friendly indication of this, just appimage is missing from the option to select, and isn't installed by default)
Clean install (debian 12/manjaro): …
=> fix: install arial font

ou_dedetai/config.py
Tested:
- removed ~/.config/Faithlife-Community/
- copied old configuration to old location
- ran install
- verified config got copied and relevant keys retained (such as product version)
=> fix: legacy config migration

ou_dedetai/config.py
Fixes: #350
Tested:
- wine 10 (has two binaries)
- wine 10 renaming wine64 to wine
- wine 10 removing wine64 (app fails as expected)
- wine 10.2 (has only wine binary that's 32bit)
- putting an empty file in wine's place - warning shown as expected.
=> fix: handle case where wine binary is 64bit

ou_dedetai/constants.py, ou_dedetai/gui.py
GUI advanced install was crashing (as there wasn't a 1st index anymore)
Constant isn't use anywhere
=> fix: cleanup logos 9

ou_dedetai/app.py, ou_dedetai/config.py, ou_dedetai/gui_app.py, ou_dedetai/installer.py, ou_dedetai/main.py, ou_dedetai/tui_app.py
Tested:
- inserting a dummy .ask in ensure_fonts
- TUI advanced install, selected logos, hit main menu on version, then went back into install. Observed main menu restored, also observed using debugger that install thread closed. Hit advanced install again and got prompt to select Logos/Verbum
- GUI, hit install, canceled from dummy question, observed install/advanced install buttons were good again, thread closed, and can hit install again
- CLI, exited from dummy question, program exits with no further text
- CLI, went through dummy question, replied Logos, then exited. Launched CLI again and was re-prompted for Logos as expected
=> fix: allow user to return to main menu during install

ou_dedetai/backup.py, ou_dedetai/utils.py, tests/test_backup.py
rather than initializing destination_dir to none, then setting it, use abstract functions to populate them.
Also standardized on logos_app_data_dir rather than using logos_app_data_dir in one operation, then logos_exe.parent in another
Resolves type issues reported by mypy
Tested:
- installed Logos, logged in, downloaded resources, made backup, deleted Data/Documents/Users, restored -> success
=> refactor: use abstract base class in backup

ou_dedetai/constants.py, ou_dedetai/network.py, ou_dedetai/tui_app.py, ou_dedetai/utils.py, ou_dedetai/wine.py, tests/test_utils.py
Also fixed XDG_DATA_HOME bug, the types were not quite right before.
Also changed the support message to be more clear to use the get support operation
Also fixed some typos where product release was substituted for product version
Tested:
- clean install with latest version -> install succeeds and required_wine_minimum is set to 9.10
- (for testing) removed TRANSFORMS, observed installer exited saying the Logos installer failed.
- `export FLPRODUCT=Logos ;export TARGETVERSION=10 ; export TARGET_RELEASE_VERSION=29.1.0.0022 ` Install using logos < 30 -> minimum wine version is 7.18
- Clean install of Logos < 29 (used same exports as above) -> no transforms
- mocked version filtering via python interactive shell
- exporting XDG_DATA_HOME -> observed Faithlife-Community folder was created …
=> fix: release version comparison

ou_dedetai/app.py, ou_dedetai/config.py, ou_dedetai/database.py, ou_dedetai/gui_app.py, ou_dedetai/logos.py, ou_dedetai/repair.py, ou_dedetai/utils.py, tests/test_utils.py
Detect First time installs and warn the user if we're still in that state. This may be useful in debugging.
It should be noted we should never see this if there was no crash, this database flag is only set during resource download before the first run dialog is closed. The first run dialog would have had to crash in order for this to display
Opted not to manually mangle the logos database into force a non-first run state due to potential side effects that may last the entire install. It's safer to act as much like the window install as we can. If push comes to shove, we can bypass it as-needed, but it may have far-reaching side effects
=> feat: detect first time installs

ou_dedetai/network.py
This assumes that there is a 1:1 relationship between steps and download jobs, which is presently true. If at some point in the future it is no longer true the worst that'll happen is the progress bar will appear to go backwards.
Tested:
- GUI clean install w/ clearing cache, observe progress bar moving as resource is downloading with human readable name
- CLI clean install w/ clearing cache, observed characters moving (there is a double line as the file is downloading (this may be fixed in the latest commit, couldn't test due to GH rate limit))
=> fix: actually move progress bar as we download

ou_dedetai/tui_app.py, ou_dedetai/tui_curses.py, ou_dedetai/tui_screen.py
Fixes #342.
Besides declaring new variables for each of the new windows, this also renames the console window to header and the menu window to main. As part of this, some of the functions needed to have the appropriate screen passed to them rather than calling that screen from the App. I tried a branch where I removed the App dependency from tui_screen.py and tui_curses.py but I was unable to get the drawing correct. I believe I need to rework that branch as I think there is some bad tracking with the new variables.
I modularize some of the bigger functions and simplify some of the functions where I could implement logic. I also swap some of the static numbers for their appropriate variable.
I also added the ability to navigate TUI menus with left and right arrow keys. What sparked the …
=> feat: TUI: add a footer window; split console into header and console windows

ou_dedetai/cli.py, ou_dedetai/config.py, ou_dedetai/control.py, ou_dedetai/gui.py, ou_dedetai/gui_app.py, ou_dedetai/main.py, ou_dedetai/tui_app.py
Fixes: https://github.com/FaithLife-Community/OuDedetai/issues/233
Removes the --remove-install-dir cli argument and adds --uninstall
Tested:
- CLI (Yes, No), (No), (Yes, Yes)
- GUI (No), (Yes, No, Then install again) (Yes, Yes). Note: This will re-create a clean config and cache after uninstall due to GUI enforcing settings
- TUI (Return to main menu), (Yes, Return to Main Menu), ((Yes, No), Install, (Yes, Yes))
=> feat: add uninstall button

.github/workflows/build-branch.yml
Fixes: #371
Accidentally got set to ubuntu-latest in recent commit, this restores the old behavior with an older glibc
=> ci: revert to older ubuntu version when building

ou_dedetai/config.py, ou_dedetai/logos.py
Some paths had a hard coded "Logos" in them
The first bug exposed by integration testing!
Tested:
- Launched Verbum
- Used oudedetai --stop-installed-app
- Verbum closed
=> fix: stop Verbum

ou_dedetai/app.py, ou_dedetai/backup.py, ou_dedetai/cli.py, ou_dedetai/config.py, ou_dedetai/control.py, ou_dedetai/gui_app.py, ou_dedetai/main.py, ou_dedetai/tui_app.py, ou_dedetai/utils.py, tests/test_backup.py, tests/test_utils.py
Get backup and restore working for CLI (prep for getting general backup/restore working)
=> fix: backup cli

ou_dedetai/constants.py
This flag is very noisy, and seldom useful for normal users.
Tested:
- Ran Logos, observed in logs fixme+all wasn't present
=> chore: remove noisy WINEDEBUG

ou_dedetai/tui_app.py
Following #379, which I merged without fully testing in order to be able to test other PRs, I found there was a regression in the PR. This turned out to be an incorrectly assigned value.
=> fix: incorrect TUI ratio value

ou_dedetai/cli.py, ou_dedetai/installer.py, ou_dedetai/logos.py, ou_dedetai/repair.py, ou_dedetai/system.py, ou_dedetai/wine.py
Logos/Verbum (Indexer) now log to the wine log file, with their previous run logging to wine.1.log
All other wine executions as part of the install process now go into OD's log
Fixes: #376
Tested:
- run logos, log is in wine.log, launching a second time, it's moved to wine.1.log, and the new one is at wine.log
- clean install (confirm log is expected)
- during install msi TRANSFORMS functions, and msiexec logs are in OD's
- winetricks logs during install are in OD's
- during install winemenubuilder/renderer/fontsmoothing logs are in OD's
- TUI set windows version
- switch Logos logging wine execution goes into OD's log (looks to be empty)
- install fonts detects existing arial font
- ran indexing (confirm log as expected)
- winetricks command, make sure stdout/stderr/exitcode are passed …
=> fix: wine logging

ou_dedetai/app.py, ou_dedetai/backup.py, ou_dedetai/cli.py, ou_dedetai/control.py, ou_dedetai/gui_app.py, ou_dedetai/tui_app.py
It should be noted this restricts the CLI to only working on *NIX system - as it uses curses
Tested:
- Ran clean install, saw progress bar and no artifacts, and after OD completed, could interact with terminal again
=> feat: add progress bar to CLI

CHANGELOG.md, ou_dedetai/constants.py
Tested:
- Clean install, running logos shows login screen for Logos 40.2
- launch TUI, shown main menu
- launch GUI, shown control panel
Post-release:
- Make sure GLIBC version is old enough
- Make sure oudedetai x86 binary is at the top and named oudedetai (may need to download the binary, rename it locally, then re-upload). This may or may not matter, our code MAY assume one name over the other.
=> chore(release): update version to 4.0.0-beta.11

snap/snapcraft.yaml
Adds wine & winetricks package dependencies to snap build; fixes #387.
=> fix: add missing wine and winetricks system dependencies

ou_dedetai/wine.py
function failed to return anything, causing it to return None which is falsy.
Regressed since 7b8b1cb6cd645d446003cfeb6158e6a3d4b8dca3 causing #396
Also fixed typo in command string generation, as exe can be None
Tested:
- Building dev binary
- Copying to effected VM
- running Logos
- Observe no crash
- Commenting out the changed line
- Building dev binary
- Copying to effected VM
- running Logos
- Observe crash
- Conclusive evidence this one line caused the issue. Probably due to multiple wine servers opening more files than they should have.
Fixes: #396
=> fix: actually check wineserver

ou_dedetai/network.py
The existing code didn't actually replace "self" so the first time the program launched with a stale cache, it actually kept the old cache's contents.
Tested:
- had a stale cache
- launched OD with attached debugger
- ensured cache did not have any values populated
=> fix: actually start with clean cache

shell.nix
Fix `"winetricks -q arial" Failed!` in `Nix/NixOS`. See https://github.com/FaithLife-Community/OuDedetai/issues/387#issuecomment-2780111636.
Need to set `config.allowUnfree = true;` because `corefonts` has unfree license.
=> fix: add missing arial font in nix

io.github.FaithlifeCommunity.OuDedetai.yml, ou_dedetai/config.py, ou_dedetai/installer.py, ou_dedetai/logos.py, ou_dedetai/system.py, snap/snapcraft.yaml
Open questions:
- snap - probably just needs a new .desktop file
- flatpak - maybe it's own desktop file
Tested (debian 12 only):
- built binary
- copied binary into clean VM
- installed Logos 40.1
- Launched Logos
- Hit "sign in" on Logos wine window
- Browser opened a window where I was asked wo "Authorize" Logos Bible Study (I was already signed in)
- Accepted the firefox prompt: "Allow this site to open the logos4 link with Logos URL Handler"?
- After saying yes, Logos said "Getting ready" and showed first run dialog as it did in 40.0 and below after logging in.
- After resources were downloaded went to a website in firefox that has a libronixdls URL (https://house.daviddgtnt.xyz/) and clicked the link
- Accepted the firefox prompt: "Allow this site to open the libronixdls link with …
=> feat: support logos4 and libronixdls URL schemes

ou_dedetai/system.py
Debian 13 actually uses libfuse3-4 not libfuse 3-3, but all the ubuntu derivatives still use libfuse3-3. Perhaps debian updated from libfuse3-3 to libfuse3-4 at some point and ubuntu hasn't/won't take this change (or yet at least).
Also the old logic doesn't install the other default package list, which it now does
Tested:
- install on debian 12 via cli - observed no failure (I did observe a failure when I tested main)
=> fix: debian 13 libfuse logic
